MAIN_LAYOUT_NAME = 'MAIN_LAYOUT'
MAIN_GRID_LAYOUT_NAME = 'MAIN_GRID_LAYOUT'

CUSTOM_SCROLLBAR_NAME = 'CUSTOM_SCROLLBAR'
TOOLBAR_SCROLL_AREA_NAME = 'TOOLBAR_SCROLL_AREA'
CONTENT_SCROLL_AREA_NAME = 'CONTENT_SCROLL_AREA'

FORM_LABEL_NAME = 'FORM_LABEL'
FORM_INPUT_NAME = 'FORM_INPUT'

LIST_ITEM_TITLE_LABEL_NAME = 'LIST_ITEM_TITLE_LABEL'
LIST_ITEM_DETAIL_LABEL_NAME = 'LIST_ITEM_DETAIL_LABEL'

TOOLBAR_BUTTON_NAME = 'TOOLBAR_BUTTON'
