MAIN_WINDOW_NAME = 'MAIN_WINDOW'

CUSTOM_VIEW_WIDGET_NAME = 'CUSTOM_VIEW_WIDGET'
MAIN_TOOLBAR_VIEW_WIDGET_NAME = 'MAIN_TOOLBAR_VIEW_WIDGET'
DB_CONNECTION_VIEW_NAME = 'DB_CONNECTION_VIEW'
APPLICATION_HOME_VIEW_NAME = 'APPLICATION_HOME_VIEW'
UR_ITEM_DETAILS_VIEW_NAME = 'UR_ITEM_DETAILS'
UR_LIST_ITEM_VIEW_NAME = 'UR_LIST_ITEM'
UR_SELECTION_LIST_VIEW_NAME = 'UR_SELECTION_LIST_VIEW'

MAIN_GRID_LAYOUT_NAME = 'MAIN_GRID_LAYOUT'

CUSTOM_SCROLLBAR_NAME = 'CUSTOM_SCROLLBAR'
TOOLBAR_SCROLL_AREA_NAME = 'TOOLBAR_SCROLL_AREA'
CONTENT_SCROLL_AREA_NAME = 'CONTENT_SCROLL_AREA'

HINT_LABEL_NAME = 'HINT_LABEL'
FORM_LABEL_NAME = 'FORM_LABEL'
FORM_INPUT_NAME = 'FORM_INPUT'

LIST_ITEM_TITLE_LABEL_NAME = 'LIST_ITEM_TITLE_LABEL'
LIST_ITEM_DETAIL_LABEL_NAME = 'LIST_ITEM_DETAIL_LABEL'

TOOLBAR_BUTTON_NAME = 'TOOLBAR_BUTTON'
ACTION_BUTTON_NAME = 'ACTION_BUTTON'
LIST_ACTION_BUTTON_NAME = 'LIST_ACTION_BUTTON'